/*
 * Copyright (c) 2014 Baidu.com, Inc. All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package com.baidubce.services.blb.model;

import java.util.List;

import com.baidubce.auth.BceCredentials;
import com.baidubce.model.AbstractBceRequest;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The request for blb listener operations.
 */
public class BlbListenerRequest extends AbstractBceRequest {

    /**
     * An ASCII string whose length is less than 64.
     * <p>
     * The request will be idempotent if clientToken is provided.
     * If the clientToken is not specified by the user, a random String generated by default algorithm will be used.
     * See more detail at
     * <a href = "https://bce.baidu.com/doc/BCC/API.html#.E5.B9.82.E7.AD.89.E6.80.A7">
     * BCE API doc</a>
     */
    @JsonIgnore
    private String clientToken;

    /**
     * the blb id of the listener.
     */
    private String blbId;
    /**
     * the backend port of the listener.
     */
    private Integer backendPort;
    /**
     * the port of the listener.
     */
    private Integer listenerPort;
    /**
     * the type of the listener.
     * <p>
     * value contains TCP|UDP|HTTP|HTTPS
     */
    @JsonIgnore
    private String type;
    /**
     * the scheduler of the listener.
     * <p>
     * the attribute exist when type is TCP|HTTP
     */
    private String scheduler;
    /**
     * if the listener keep session or not.
     * <p>
     * the attribute exist when type is TCP|HTTP
     */
    private boolean keepSession;
    /**
     * the type of keep session.
     */
    private String keepSessionType;
    /**
     * the duration of keep session.
     */
    @JsonProperty("keepSessionTimeout")
    private Integer keepSessionDuration;
    /**
     * the cookie name of keep session.
     */
    private String keepSessionCookieName;
    /**
     * if the listener fetch the real ip or not.
     * <p>
     * the attribute exist when type is HTTP.
     */
    @JsonProperty("xForwardedFor")
    private boolean xForwardFor;
    /**
     * the type of health check.
     * <p>
     * the attribute exist when type is HTTP.
     */
    private String healthCheckType;
    /**
     * the port of the health check.
     */
    private Integer healthCheckPort;
    /**
     * the timeout of the health check.
     */
    private Integer healthCheckTimeoutInSecond;
    /**
     * the threshold of unhealthy.
     */
    private Integer unhealthyThreshold;
    /**
     * the threshold of healthy.
     */
    private Integer healthyThreshold;
    /**
     * the interval of the health check.
     */
    private Integer healthCheckInterval;
    /**
     * the uri of health check.
     */
    private String healthCheckURI;
    /**
     * the status of health check when it is normal.
     */
    private String healthCheckNormalStatus;
    /**
     * the max timeout of server.
     */
    private Integer serverTimeout;
    /**
     * the certificate ids of listener.
     */
    private List<String> certIds;
    /**
     * The additional certificates and domains of listener
     * @see AdditionalCertDomain
     */
    private List<AdditionalCertDomain> additionalCertDomains;
    /**
     * if the request is ie6 compatible or not.
     */
    private Boolean ie6Compatible;
    /**
     * the port of redirect.
     */
    private Integer redirectPort;
    /**
     * the string to health check when type is UDP
     */
    private String healthCheckString;

    /**
     * tcp session timeout (seconds), default 900, range 10-4000
     * the attribute exist when type is TCP
     */
    private Integer tcpSessionTimeout;

    /**
     * udp session timeout (seconds), default 90, range 5-4000
     * the attribute exist when type is UDP
     */
    private Integer udpSessionTimeout;

    /**
     * forward the protocol to backend server via x-forwarded-proto HTTP Header
     * the attribute exist when type is HTTP/HTTPS
     */
    @JsonProperty("xForwardedProto")
    private Boolean xForwardedProto;

    /**
     * additional attributes for HTTP/HTTPS listener
     */
    private AdditionalAttributes additionalAttributes;

    /**
     * health check host for 7-layer health check
     * the attribute exist when type is HTTP/HTTPS
     */
    private String healthCheckHost;

    /**
     * encryption type for SSL/HTTPS listener
     */
    private String encryptionType;

    /**
     * encryption protocols for SSL/HTTPS listener when encryptionType is userDefind
     */
    private List<String> encryptionProtocols;

    /**
     * applied ciphers for SSL/HTTPS listener
     */
    private String appliedCiphers;

    /**
     * open dual auth or not for SSL/HTTPS listener
     */
    private Boolean dualAuth;

    /**
     * client cert ids for SSL/HTTPS listener when dualAuth is true
     */
    private List<String> clientCertIds;

    /**
     * the description of the listener, no more than 200 characters
     */
    private String description;

    public String getClientToken() {
        return clientToken;
    }

    public void setClientToken(String clientToken) {
        this.clientToken = clientToken;
    }

    public String getBlbId() {
        return blbId;
    }

    public void setBlbId(String blbId) {
        this.blbId = blbId;
    }

    public Integer getBackendPort() {
        return backendPort;
    }

    public void setBackendPort(Integer backendPort) {
        this.backendPort = backendPort;
    }

    public Integer getListenerPort() {
        return listenerPort;
    }

    public void setListenerPort(Integer listenerPort) {
        this.listenerPort = listenerPort;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getScheduler() {
        return scheduler;
    }

    public void setScheduler(String scheduler) {
        this.scheduler = scheduler;
    }

    public boolean isKeepSession() {
        return keepSession;
    }

    public void setKeepSession(boolean keepSession) {
        this.keepSession = keepSession;
    }

    public String getKeepSessionType() {
        return keepSessionType;
    }

    public void setKeepSessionType(String keepSessionType) {
        this.keepSessionType = keepSessionType;
    }

    public Integer getKeepSessionDuration() {
        return keepSessionDuration;
    }

    public void setKeepSessionDuration(Integer keepSessionDuration) {
        this.keepSessionDuration = keepSessionDuration;
    }

    public String getKeepSessionCookieName() {
        return keepSessionCookieName;
    }

    public void setKeepSessionCookieName(String keepSessionCookieName) {
        this.keepSessionCookieName = keepSessionCookieName;
    }

    public boolean isxForwardFor() {
        return xForwardFor;
    }

    public void setxForwardFor(boolean xForwardFor) {
        this.xForwardFor = xForwardFor;
    }

    public String getHealthCheckType() {
        return healthCheckType;
    }

    public void setHealthCheckType(String healthCheckType) {
        this.healthCheckType = healthCheckType;
    }

    public Integer getHealthCheckPort() {
        return healthCheckPort;
    }

    public void setHealthCheckPort(Integer healthCheckPort) {
        this.healthCheckPort = healthCheckPort;
    }

    public Integer getHealthCheckTimeoutInSecond() {
        return healthCheckTimeoutInSecond;
    }

    public void setHealthCheckTimeoutInSecond(Integer healthCheckTimeoutInSecond) {
        this.healthCheckTimeoutInSecond = healthCheckTimeoutInSecond;
    }

    public Integer getUnhealthyThreshold() {
        return unhealthyThreshold;
    }

    public void setUnhealthyThreshold(Integer unhealthyThreshold) {
        this.unhealthyThreshold = unhealthyThreshold;
    }

    public Integer getHealthyThreshold() {
        return healthyThreshold;
    }

    public void setHealthyThreshold(Integer healthyThreshold) {
        this.healthyThreshold = healthyThreshold;
    }

    public Integer getHealthCheckInterval() {
        return healthCheckInterval;
    }

    public void setHealthCheckInterval(Integer healthCheckInterval) {
        this.healthCheckInterval = healthCheckInterval;
    }

    public String getHealthCheckURI() {
        return healthCheckURI;
    }

    public void setHealthCheckURI(String healthCheckURI) {
        this.healthCheckURI = healthCheckURI;
    }

    public String getHealthCheckNormalStatus() {
        return healthCheckNormalStatus;
    }

    public void setHealthCheckNormalStatus(String healthCheckNormalStatus) {
        this.healthCheckNormalStatus = healthCheckNormalStatus;
    }

    public Integer getServerTimeout() {
        return serverTimeout;
    }

    public void setServerTimeout(Integer serverTimeout) {
        this.serverTimeout = serverTimeout;
    }

    public List<String> getCertIds() {
        return certIds;
    }

    public void setCertIds(List<String> certIds) {
        this.certIds = certIds;
    }

    public List<AdditionalCertDomain> getAdditionalCertDomains() {
        return additionalCertDomains;
    }

    public void setAdditionalCertDomains(
            List<AdditionalCertDomain> additionalCertDomains) {
        this.additionalCertDomains = additionalCertDomains;
    }

    public Boolean getIe6Compatible() {
        return ie6Compatible;
    }

    public void setIe6Compatible(Boolean ie6Compatible) {
        this.ie6Compatible = ie6Compatible;
    }

    public Integer getRedirectPort() {
        return redirectPort;
    }

    public void setRedirectPort(Integer redirectPort) {
        this.redirectPort = redirectPort;
    }

    public String getHealthCheckString() {
        return healthCheckString;
    }

    public void setHealthCheckString(String healthCheckString) {
        this.healthCheckString = healthCheckString;
    }

    public Integer getTcpSessionTimeout() {
        return tcpSessionTimeout;
    }

    public void setTcpSessionTimeout(Integer tcpSessionTimeout) {
        this.tcpSessionTimeout = tcpSessionTimeout;
    }

    public Integer getUdpSessionTimeout() {
        return udpSessionTimeout;
    }

    public void setUdpSessionTimeout(Integer udpSessionTimeout) {
        this.udpSessionTimeout = udpSessionTimeout;
    }

    public Boolean getxForwardedProto() {
        return xForwardedProto;
    }

    public void setxForwardedProto(Boolean xForwardedProto) {
        this.xForwardedProto = xForwardedProto;
    }

    public AdditionalAttributes getAdditionalAttributes() {
        return additionalAttributes;
    }

    public void setAdditionalAttributes(AdditionalAttributes additionalAttributes) {
        this.additionalAttributes = additionalAttributes;
    }

    public String getHealthCheckHost() {
        return healthCheckHost;
    }

    public void setHealthCheckHost(String healthCheckHost) {
        this.healthCheckHost = healthCheckHost;
    }

    public String getEncryptionType() {
        return encryptionType;
    }

    public void setEncryptionType(String encryptionType) {
        this.encryptionType = encryptionType;
    }

    public List<String> getEncryptionProtocols() {
        return encryptionProtocols;
    }

    public void setEncryptionProtocols(List<String> encryptionProtocols) {
        this.encryptionProtocols = encryptionProtocols;
    }

    public String getAppliedCiphers() {
        return appliedCiphers;
    }

    public void setAppliedCiphers(String appliedCiphers) {
        this.appliedCiphers = appliedCiphers;
    }

    public Boolean getDualAuth() {
        return dualAuth;
    }

    public void setDualAuth(Boolean dualAuth) {
        this.dualAuth = dualAuth;
    }

    public List<String> getClientCertIds() {
        return clientCertIds;
    }

    public void setClientCertIds(List<String> clientCertIds) {
        this.clientCertIds = clientCertIds;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public BlbListenerRequest withRequestCredentials(BceCredentials credentials) {
        this.setRequestCredentials(credentials);
        return this;
    }
}
