/*
 * Copyright (C) 2019 Baidu, Inc. All Rights Reserved.
 */
package com.baidubce.services.ipv6Gateway.model;

import com.baidubce.auth.BceCredentials;
import com.baidubce.model.AbstractBceRequest;
import com.baidubce.services.bcc.model.TagModel;
import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.List;

/**
 * The request for creating a newly Ipv6Gateway.
 */
public class CreateIpv6GatewayRequest extends AbstractBceRequest {

    /**
     * An ASCII string whose length is less than 64.
     * <p>
     * The request will be idempotent if clientToken is provided.
     * If the clientToken is not specified by the user, a random String generated by default algorithm will be used.
     * See more detail at
     * <a href = "https://bce.baidu.com/doc/BCC/API.html#.E5.B9.82.E7.AD.89.E6.80.A7">
     * BCE API doc</a>
     */
    @JsonIgnore
    private String clientToken;

    /**
     * The name of Ipv6Gateway that will be created.
     */
    private String name;

    /**
     * The vpcId of this Ipv6Gateway belong.
     */
    private String vpcId;

    /**
     * The bandwidthInMbps of Ipv6Gateway that will be created.
     */
    private int bandwidthInMbps;

    private Billing billing;

    /**
     * The tags of Ipv6Gateway that will be created.
     */
    private List<TagModel> tags;

    /**
     * The resourceGroupId of Ipv6Gateway that will be created.
     */
    private String resourceGroupId;

    /**
     * Whether to enable delete protection. Default is false.
     */
    private Boolean deleteProtect;

    public String getClientToken() {
        return clientToken;
    }

    public void setClientToken(String clientToken) {
        this.clientToken = clientToken;
    }

    /**
     * Configure request credential for the request.
     *
     * @param credentials a valid instance of BceCredentials.
     *
     * @return CreateIpv6GatewayRequest with credentials.
     */
    public CreateIpv6GatewayRequest withRequestCredentials(BceCredentials credentials) {
        this.setRequestCredentials(credentials);
        return this;
    }

    /**
     * Configure name for the request.
     *
     * @param name The name of vpc
     *
     * @return CreateIpv6GatewayRequest with specific name
     */
    public CreateIpv6GatewayRequest withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Configure vpcId for the request.
     *
     * @param vpcId the vpcId of Ipv6Gateway
     *
     * @return CreateIpv6GatewayRequest with vpcId
     */
    public CreateIpv6GatewayRequest withVpcId(String vpcId) {
        this.vpcId = vpcId;
        return this;
    }

    /**
     * Configure bandwidthInMbps for the request.
     *
     * @param bandwidthInMbps the bandwidthInMbps of Ipv6Gateway
     *
     * @return CreateIpv6GatewayRequest with bandwidthInMbps
     */
    public CreateIpv6GatewayRequest withBandwith(int bandwidthInMbps) {
        this.bandwidthInMbps = bandwidthInMbps;
        return this;
    }

    /**
     * Configure bandwidthInMbps for the request.
     *
     * @param billing the Billing of Ipv6Gateway
     *
     * @return CreateIpv6GatewayRequest with billing
     */
    public CreateIpv6GatewayRequest withBilling(Billing billing) {
        this.billing = billing;
        return this;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getVpcId() {
        return vpcId;
    }

    public void setVpcId(String vpcId) {
        this.vpcId = vpcId;
    }

    public int getBandwidthInMbps() {
        return bandwidthInMbps;
    }

    public void setBandwidthInMbps(int bandwidthInMbps) {
        this.bandwidthInMbps = bandwidthInMbps;
    }

    public Billing getBilling() {
        return billing;
    }

    public void setBilling(Billing billing) {
        this.billing = billing;
    }

    public List<TagModel> getTags() {
        return tags;
    }

    public void setTags(List<TagModel> tags) {
        this.tags = tags;
    }

    /**
     * Configure tags for the request.
     *
     * @param tags The tags of Ipv6Gateway
     *
     * @return CreateIpv6GatewayRequest with tags
     */
    public CreateIpv6GatewayRequest withTags(List<TagModel> tags) {
        this.tags = tags;
        return this;
    }

    public String getResourceGroupId() {
        return resourceGroupId;
    }

    public void setResourceGroupId(String resourceGroupId) {
        this.resourceGroupId = resourceGroupId;
    }

    /**
     * Configure resourceGroupId for the request.
     *
     * @param resourceGroupId The resourceGroupId of Ipv6Gateway
     *
     * @return CreateIpv6GatewayRequest with resourceGroupId
     */
    public CreateIpv6GatewayRequest withResourceGroupId(String resourceGroupId) {
        this.resourceGroupId = resourceGroupId;
        return this;
    }

    public Boolean getDeleteProtect() {
        return deleteProtect;
    }

    public void setDeleteProtect(Boolean deleteProtect) {
        this.deleteProtect = deleteProtect;
    }

    /**
     * Configure deleteProtect for the request.
     *
     * @param deleteProtect Whether to enable delete protection
     *
     * @return CreateIpv6GatewayRequest with deleteProtect
     */
    public CreateIpv6GatewayRequest withDeleteProtect(Boolean deleteProtect) {
        this.deleteProtect = deleteProtect;
        return this;
    }

}
