/*
 * Copyright (C) 2016 Baidu, Inc. All Rights Reserved.
 */
package com.baidubce.services.eip.model;

import com.baidubce.auth.BceCredentials;
import com.baidubce.model.AbstractBceRequest;
import com.baidubce.services.bcc.model.TagModel;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Getter;
import lombok.Setter;

import java.util.List;

/**
 * The request for creating a newly eip.
 */
@Getter
@Setter
public class CreateEipRequest extends AbstractBceRequest {
    /**
     * If the clientToken is not specified by the user, a random String generated by default algorithm will be used.
     * See more detail at
     * <a href = "https://bce.baidu.com/doc/EIP/API.html#.E9.80.9A.E7.94.A8.E8.AF.B4.E6.98.8E">
     *   BCE API doc</a>
     */
    @JsonIgnore
    private String clientToken;
    /**
     * name of eip. The optional parameter
     */
    private String name;
    /**
     * specify the bandwidth in Mbps
     */
    private Integer bandwidthInMbps;
    /**
     * billing information. The optional parameter, default paymentTiming is Postpaid
     */
    private Billing billing;

    /**
     * The tags which will be bound to eip.
     */
    private List<TagModel> tags;

    /**
     * The ID of resourceGroup which will be bound to eip.
     */
    private String resourceGroupId;

    /**
     * eip route type
     */
    private String routeType;

    /**
     * EIP IP类型, ipv4或ipv6, 默认ipv4
     */
    private String ipVersion;

    /**
     * 自动续费时间单位, month或year, 默认month
     */
    private String autoRenewTimeUnit;

    /**
     * 自动续费时长
     */
    private Integer autoRenewTime;

    /**
     * 是否开启释放保护, 默认false
     */
    private Boolean deleteProtect;

    public CreateEipRequest withIpVersion(String ipVersion) {
        this.ipVersion = ipVersion;
        return this;
    }

    public CreateEipRequest withAutoRenewTimeUnit(String autoRenewTimeUnit) {
        this.autoRenewTimeUnit = autoRenewTimeUnit;
        return this;
    }

    public CreateEipRequest withAutoRenewTime(Integer autoRenewTime) {
        this.autoRenewTime = autoRenewTime;
        return this;
    }

    public CreateEipRequest withDeleteProtect(Boolean deleteProtect) {
        this.deleteProtect = deleteProtect;
        return this;
    }

    public CreateEipRequest withClientToken(String clientToken) {
        this.clientToken = clientToken;
        return this;
    }

    public CreateEipRequest withName(String name) {
        this.name = name;
        return this;
    }

    public CreateEipRequest withBandwidthInMbps(Integer bandwidthInMbps) {
        this.bandwidthInMbps = bandwidthInMbps;
        return this;
    }

    public CreateEipRequest withBilling(Billing billing) {
        this.billing = billing;
        return this;
    }

    public CreateEipRequest withTags(List<TagModel> tags) {
        this.tags = tags;
        return this;
    }

    public CreateEipRequest withResourceGroupId(String resourceGroupId) {
        this.resourceGroupId = resourceGroupId;
        return this;
    }

    public CreateEipRequest withRequestCredentials(BceCredentials credentials) {
        this.setRequestCredentials(credentials);
        return this;
    }

    public CreateEipRequest withRouteType(String routeType) {
        this.routeType = routeType;
        return this;
    }

}
