package com.baidubce.services.nat.model;

import java.util.List;

import com.baidubce.auth.BceCredentials;
import com.baidubce.model.AbstractBceRequest;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * The request for enhance nat binding eip.
 */
public class EnhanceNatBindEipRequest extends AbstractBceRequest {

    /**
     * An ASCII string whose length is less than 64.
     *
     * The request will be idempotent if clientToken is provided.
     * If the clientToken is not specified by the user, a random String generated by default algorithm will be used.
     * See more detail at
     * <a href = "https://bce.baidu.com/doc/BCC/API.html#.E5.B9.82.E7.AD.89.E6.80.A7">
     *     BCE API doc</a>
     */
    @JsonIgnore
    private String clientToken;

    /**
     * Eip addresses to be bound
     */
    private List<String> bindEips;

    /**
     * The natId of nat to be bound.
     */
    @JsonIgnore
    private String natId;

    /**
     * Configure natId for the request.
     *
     * @param natId NatId to be bound
     * @return BindEipRequest with specific natId
     */
    public EnhanceNatBindEipRequest withNatId(String natId) {
        this.natId = natId;
        return this;
    }

    /**
     * Configure eips for the request.
     *
     * @param bindEips Eip addresses to be bound
     * @return BindEipRequest with specific eips
     */
    public EnhanceNatBindEipRequest withBindEips(List<String> bindEips) {
        this.bindEips = bindEips;
        return this;
    }

    public List<String> getBindEips() {
        return bindEips;
    }

    public void setBindEips(List<String> bindEips) {
        this.bindEips = bindEips;
    }

    public String getNatId() {
        return natId;
    }

    public void setNatId(String natId) {
        this.natId = natId;
    }

    public String getClientToken() {
        return clientToken;
    }

    public void setClientToken(String clientToken) {
        this.clientToken = clientToken;
    }

    @Override
    public AbstractBceRequest withRequestCredentials(BceCredentials credentials) {
        return null;
    }
}
