package com.baidubce.services.bec.model.appblbv2.backendbind;

import com.baidubce.auth.BceCredentials;
import com.baidubce.model.AbstractBceRequest;
import com.baidubce.services.bec.model.vo.v2.ListRequest;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
/**
 * @Author wangjiang07
 * @Since 2025-08-04 10:10
 * @Version v1.0
 * the request for getting app blb server group unmounted members
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class GetBecAppBlbServerGroupUnmountedMembersRequest extends AbstractBceRequest {

    private String blbId;
    private String sgId;
    private ListRequest listRequest;
    /**
     * An ASCII string whose length is less than 64.
     * <p>
     * The request will be idempotent if clientToken is provided.
     * If the clientToken is not specified by the user, a random String generated by default algorithm will be used.
     * See more detail at
     * <a href = "">
     * https://bce.baidu.com/doc/BEC/API.html
     * BCE API doc</a>
     */
    @JsonIgnore
    private String clientToken;

    /**
     * Configure request credential for the request.
     *
     * @param credentials a valid instance of BceCredentials.
     * @return Request entity with credentials.
     */
    public GetBecAppBlbServerGroupUnmountedMembersRequest withRequestCredentials(BceCredentials credentials) {
        this.setRequestCredentials(credentials);
        return this;
    }
}
