package com.baidubce.services.bcc.model.securitygroup;

import com.baidubce.auth.BceCredentials;
import com.baidubce.model.AbstractBceRequest;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
/**
 * The request for delete SecurityGroupRule
 */
public class DeleteSecurityGroupRuleRequest extends AbstractBceRequest {

    /**
     * The id of the security group rule
     */
    private String securityGroupRuleId;

    /**
     * The security group version number
     */
    private Long sgVersion;

    /**
     * An ASCII string whose length is less than 64.
     * The request will be idempotent if client token is provided.
     * If the clientToken is not specified by the user, a random String generated by default algorithm will be used.
     */
    @JsonIgnore
    private String clientToken;

    /**
     * Configure security group rule id for the request.
     *
     * @param securityGroupRuleId The rule id of the security group to be deleted.
     * @return DeleteSecurityGroupRuleRequest with security group rule id.
     */
    public DeleteSecurityGroupRuleRequest withSecurityGroupRuleId(String securityGroupRuleId) {
        this.securityGroupRuleId = securityGroupRuleId;
        return this;
    }

    /**
     * Configure security group version for the request.
     *
     * @param sgVersion The security group version number.
     * @return DeleteSecurityGroupRuleRequest with sgVersion.
     */
    public DeleteSecurityGroupRuleRequest withSgVersion(Long sgVersion) {
        this.sgVersion = sgVersion;
        return this;
    }

    /**
     * Configure clientToken for the request.
     *
     * @param clientToken The clientToken for idempotence.
     * @return DeleteSecurityGroupRuleRequest with clientToken.
     */
    public DeleteSecurityGroupRuleRequest withClientToken(String clientToken) {
        this.clientToken = clientToken;
        return this;
    }

    /**
     * Configure request credential for the request.
     *
     * @param credentials a valid instance of BceCredentials.
     * @return DeleteSecurityGroupRuleRequest with credentials.
     */
    @Override
    public DeleteSecurityGroupRuleRequest withRequestCredentials(BceCredentials credentials) {
        this.setRequestCredentials(credentials);
        return this;
    }
}
