package com.baidubce.services.bcc.model.securitygroup;

import com.baidubce.auth.BceCredentials;
import com.baidubce.model.AbstractBceRequest;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
/**
 * The request for updateSecurityGroupRule
 */
public class UpdateSecurityGroupRuleRequest extends AbstractBceRequest {

    /**
     * The id of the security group rule to be updated
     */
    private String securityGroupRuleId;

    /**
     * The security group version number
     */
    @JsonIgnore
    private Long sgVersion;

    /**
     * An ASCII string whose length is less than 64.
     * The request will be idempotent if client token is provided.
     * If the clientToken is not specified by the user, a random String generated by default algorithm will be used.
     */
    @JsonIgnore
    private String clientToken;

    /**
     * The remark of the security group rule
     */
    private String remark;

    /**
     * The port range of the security group rule
     */
    private String portRange;

    /**
     * The source ip of the security group rule
     */
    private String sourceIp;

    /**
     * The id of the source security group
     */
    private String sourceGroupId;

    /**
     * The destination ip address
     */
    private String destIp;

    /**
     * The id of the destination security group
     */
    private String destGroupId;

    /**
     * The protocol type
     */
    private String protocol;

    /**
     * Configure sgVersion for the request.
     *
     * @param sgVersion The security group version number.
     * @return UpdateSecurityGroupRuleRequest with sgVersion.
     */
    public UpdateSecurityGroupRuleRequest withSgVersion(Long sgVersion) {
        this.sgVersion = sgVersion;
        return this;
    }

    /**
     * Configure clientToken for the request.
     *
     * @param clientToken The clientToken for idempotence.
     * @return UpdateSecurityGroupRuleRequest with clientToken.
     */
    public UpdateSecurityGroupRuleRequest withClientToken(String clientToken) {
        this.clientToken = clientToken;
        return this;
    }

    /**
     * Configure request credential for the request.
     *
     * @param credentials a valid instance of BceCredentials.
     * @return UpdateSecurityGroupRuleRequest with credentials.
     */
    @Override
    public UpdateSecurityGroupRuleRequest withRequestCredentials(BceCredentials credentials) {
        this.setRequestCredentials(credentials);
        return this;
    }
}
